apiVersion: v1
kind: Service

metadata:
  name: karsajobs-ui
  namespace: karsajobs-ns
  labels:
    app: frontend

spec:
  selector:
    app: frontend
  ports:
  # List of ports to be exposed
  - port: 8000
  # Type of the service to be exposed
  type: NodePort