apiVersion: apps/v1
kind: Deployment

metadata:
  name: karsajobs-ui
  namespace: karsajobs-ns
  labels:
    app: frontend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
      - name: karsajobs-ui
        image: ghcr.io/9lan/karsajobs-ui:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            # Memory/RAM to be used
            memory: "1Gi"
            # CPU size to be used
            cpu: "750m"
        # List of ports to be exposed
        ports:
        - containerPort: 8000
        # Env variables to set in the container
        env:
          - name: VUE_APP_BACKEND
            value: http://127.0.0.1:31253