apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs
  namespace: karsajobs-ns
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: karsajobs
        image: ghcr.io/9lan/karsajobs:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            # CPU size to be used
            cpu: "250m"
            # Memory/RAM to be used
            memory: "256Mi"
        ports:
        # Port to be exposed on the pod's IP address
        - containerPort: 8080
        # Env variables to set in the container
        env:
          - name: APP_PORT
            value: "8080"
          - name: MONGO_HOST
            value: mongo
          - name: MONGO_USER
            # Source for the environment variable's value
            valueFrom:
              # Selects a key of a secret in the pod's namespace
              secretKeyRef:
                name: mongo-secret
                key: MONGO_ROOT_USERNAME
          - name: MONGO_PASS
            # Source for the environment variable's value
            valueFrom:
              # Selects a key of a secret in the pod's namespace
              secretKeyRef:
                name: mongo-secret
                key: MONGO_ROOT_PASSWORD