apiVersion: v1
kind: Service
metadata:
  name: karsajobs
  namespace: karsajobs-ns
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  # Port to be exposed on the pod's IP address
  - port: 8080
  # Type of the service to be exposed
  type: NodePort
  