apiVersion: v1
kind: ConfigMap

metadata:
  name: mongo-config
  namespace: karsajobs-ns

# Data contains the configuration data
data:
  # Name of the configuration will be created
  mongo.conf: |
    storage:
      dbpath: /data/db